import { describe,it,expect,vi,afterEach } from 'vitest';
import { StatisticsService } from '../src/services/StatisticsService';
import { OfflineLibraryService } from '../src/services/OfflineLibraryService';
import { PlaylistService } from '../src/services/PlaylistService';
import { AudioPlayerService } from '../src/services/AudioPlayerService';
import { LocalFileSongImporter } from '../src/patterns/factory/SongImporter';
import type { LocalRepository, RepositoryStore } from '../src/storage/IndexedDbRepository';
import { FakeOutput,source,song } from './helpers';
class MemoryRepository implements LocalRepository {
  readonly data=new Map<string,unknown>();
  async read<T>(store: RepositoryStore,key: string): Promise<T|undefined>{return this.data.get(store+key) as T|undefined;}
  async write(store: RepositoryStore,key: string,value: unknown): Promise<void>{this.data.set(store+key,value);}
  async remove(store: RepositoryStore,key: string): Promise<void>{this.data.delete(store+key);}
}
afterEach(()=>vi.useRealTimers());
const setup=()=>{const repository=new MemoryRepository(),playlists=new PlaylistService({load:()=>[],save:()=>true}),importer=new LocalFileSongImporter({create:()=>source()});return {repository,playlists,importer,offline:new OfflineLibraryService(repository,playlists,importer)};};
describe('Statistics and authorized persistence',()=>{
  it('counts only listened threshold, once per session; persists ranking and days',async()=>{vi.useFakeTimers();const repository=new MemoryRepository(),player=new AudioPlayerService(new FakeOutput(),{initialVolume:.5,fadeDuration:1000,boostFactor:1.35});const stats=new StatisticsService(repository,player,()=>new Date('2026-10-07T12:00:00Z'));const event={sessionId:'session',songId:'a',playlistId:'p',playlistName:'Playlist',title:'Track',seconds:2};player.dispatchEvent(new CustomEvent('trackstart',{detail:event}));expect(stats.snapshot.totalPlays).toBe(0);stats.record(event);stats.record(event);expect(stats.snapshot.totalPlays).toBe(0);stats.record({...event,seconds:1});stats.record({...event,seconds:2});expect(stats.snapshot.totalPlays).toBe(1);expect(stats.snapshot.totalSeconds).toBe(7);expect(stats.snapshot.recent).toHaveLength(1);await stats.flush();const restored=new StatisticsService(repository,player);await restored.restore();expect(restored.snapshot.totalPlays).toBe(1);expect(restored.snapshot.songs.a.plays).toBe(1);stats.dispose();restored.dispose();});
  it('does not count seeking or repeated timeupdate positions',async()=>{vi.useFakeTimers();vi.setSystemTime(1000);const repository=new MemoryRepository(),output=new FakeOutput(),player=new AudioPlayerService(output,{initialVolume:.5,fadeDuration:1000,boostFactor:1.35});const playlists=new PlaylistService({load:()=>[],save:()=>true});const track=song();track.duration=100;playlists.active.songs.addLast(track);player.attach(playlists.active);const stats=new StatisticsService(repository,player);await player.play();vi.setSystemTime(2000);output.element.currentTime=1;output.element.dispatchEvent(new Event('timeupdate'));output.element.dispatchEvent(new Event('timeupdate'));player.seek(.8);vi.setSystemTime(3000);output.element.dispatchEvent(new Event('timeupdate'));expect(stats.snapshot.totalSeconds).toBe(1);expect(stats.snapshot.totalPlays).toBe(0);stats.dispose();});
  it('stores blobs only after consent and rebuilds songs with new URLs and stable ids',async()=>{const {repository,playlists,offline,importer}=setup();const a=importer.import(new File(['audio'],'a.wav',{type:'audio/wav'})),b=importer.import(new File(['audio'],'b.wav',{type:'audio/wav'}));playlists.active.songs.addLast(a);playlists.active.songs.addLast(b);playlists.active.repeatMode='shuffle';await offline.setSaved([a],true);const restored=new PlaylistService({load:()=>[],save:()=>true}),restorer=new OfflineLibraryService(repository,restored,importer);await restorer.restore();expect(restored.active.id).toBe(playlists.active.id);expect(restored.active.repeatMode).toBe('shuffle');expect(restored.active.songs.getSize()).toBe(1);expect(restored.active.songs.head?.song.id).toBe(a.id);expect(restorer.missingFiles).toBe(1);restored.active.songs.assertIntegrity();await restorer.clearAudio();const again=new PlaylistService({load:()=>[],save:()=>true});await new OfflineLibraryService(repository,again,importer).restore();expect(again.active.songs.isEmpty()).toBe(true);});
  it('reports quota errors, rolls back consent and preserves the in-memory playlist',async()=>{const {repository,playlists,offline,importer}=setup();const track=importer.import(new File(['audio'],'a.wav',{type:'audio/wav'}));playlists.active.songs.addLast(track);vi.spyOn(repository,'write').mockRejectedValue(new DOMException('Full','QuotaExceededError'));await expect(offline.savePlaylist(playlists.active)).rejects.toThrow();expect(offline.status).toContain('lleno');expect(track.savedOffline).toBe(false);expect(playlists.active.songs.getSize()).toBe(1);expect(offline.busy).toBe(false);});
});

it('rejects corrupted persisted statistics without presenting invalid dates or values',async()=>{
  const repository=new MemoryRepository(),player=new AudioPlayerService(new FakeOutput(),{initialVolume:.5,fadeDuration:1000,boostFactor:1.35});await repository.write('statistics','current',{version:1,totalSeconds:2,totalPlays:1,songs:{bad:{id:'bad',title:9,seconds:2,plays:1}},playlists:{},days:{},recent:[]});const statistics=new StatisticsService(repository,player);await expect(statistics.restore()).rejects.toThrow('Invalid statistics record');expect(statistics.snapshot.totalPlays).toBe(0);statistics.dispose();
});
