import { describe, it, expect } from 'vitest';
import { DoublyLinkedList } from '../src/structures/DoublyLinkedList';
import { PlaybackQueue } from '../src/services/PlaybackQueue';
import { PlaylistService } from '../src/services/PlaylistService';
import { PlaylistEditor } from '../src/services/PlaylistEditor';
import { AudioPlayerService } from '../src/services/AudioPlayerService';
import { FakeOutput, song } from './helpers';
const setup = () => { const service=new PlaylistService({load:()=>[],save:()=>true}); const player=new AudioPlayerService(new FakeOutput(),{initialVolume:.65,fadeDuration:1000,boostFactor:1.35}); player.attach(service.active); return {service,player,editor:new PlaylistEditor(service,player)}; };
describe('Advanced linked structures',()=>{
  it.each([[0,3],[3,0],[1,2],[2,1],[0,0]])('moves node %i to %i without changing current or size',(from,to)=>{const list=new DoublyLinkedList(); for(const id of ['a','b','c','d'])list.addLast({id});list.setCurrent('b');const current=list.current;const moved=list.readSnapshot()[from].id;list.moveNode(from,to);list.assertIntegrity();expect(list.current).toBe(current);expect(list.getSize()).toBe(4);expect(list.getAt(to).id).toBe(moved);});
  it('validates empty/single lists and snapshots expose no mutable nodes',()=>{const list=new DoublyLinkedList();expect(()=>list.moveNode(0,0)).toThrow();list.addFirst({id:'a'});list.moveNode(0,0);list.assertIntegrity();const snapshot=list.readSnapshot();expect(Object.isFrozen(snapshot)).toBe(true);expect(Object.isFrozen(snapshot[0])).toBe(true);expect(snapshot[0]).toMatchObject({isHead:true,isTail:true,isCurrent:true,previousId:null,nextId:null});});
  it('maintains integrity after 500 node moves',()=>{const list=new DoublyLinkedList();for(let i=0;i<12;i++)list.addLast({id:String(i)});const reference=[...list].map(item=>item.id);for(let i=0;i<500;i++){const from=i%12,to=(i*7+3)%12;const [id]=reference.splice(from,1);reference.splice(to,0,id);list.moveNode(from,to);list.assertIntegrity();expect([...list].map(item=>item.id)).toEqual(reference);}});
  it('queue prioritizes first, reorders and purges deleted sources',()=>{const queue=new PlaybackQueue();const a=song('A'),b=song('B');queue.add(a,'p','Playlist');queue.add(b,'p','Playlist',true);expect(queue.entries.head?.song.song.title).toBe('B');queue.move(queue.entries.head!.song.id,1);queue.entries.assertIntegrity();const taken=queue.take()!;expect(taken.song.title).toBe('A');taken.song.dispose();queue.forget('p');expect(queue.entries.isEmpty()).toBe(true);});
  it('undo/redo adds, removes, moves and renames without corrupting links',()=>{const {service,editor}=setup();const playlist=service.active,a=song('A'),b=song('B');editor.add(playlist,a,0,'first');editor.add(playlist,b,1,'last');editor.move(playlist,b.id,0);expect(playlist.songs.head?.song).toBe(b);editor.undo();expect(playlist.songs.head?.song).toBe(a);editor.redo();editor.remove(playlist,b.id);editor.undo();playlist.songs.assertIntegrity();expect(playlist.songs.head?.song).toBe(b);editor.rename(playlist,'New');editor.undo();expect(playlist.name).toBe('Favoritas');editor.add(playlist,song('C'),2);expect(editor.history.canRedo).toBe(false);editor.history.clear();playlist.songs.assertIntegrity();});
  it('undo restores a deleted playlist and duplicate nodes stay independent',()=>{const {service,editor}=setup();const original=service.active;editor.add(original,song(),0);const copy=editor.duplicate(original);expect(copy.songs.head).not.toBe(original.songs.head);editor.undo();expect(service.playlists.size).toBe(1);editor.redo();editor.delete(copy);editor.undo();expect(service.active).toBe(copy);editor.delete(original);editor.delete(copy);expect(service.playlists.size).toBe(1);editor.undo();expect(service.active).toBe(copy);copy.songs.assertIntegrity();});
  it('queue has priority over repeat one and returns to the playlist anchor',async()=>{const {service,player}=setup();const playlist=service.active,a=song('A'),b=song('B'),x=song('X');playlist.songs.addLast(a);playlist.songs.addLast(b);player.sync();player.setMode('one');player.queue.add(x,'other','Other',true);await player.play();await player.next();expect(player.song?.title).toBe('X');expect(playlist.songs.current?.song).toBe(a);await player.next();expect(player.song).toBe(b);player.dispose();});
  it('purges queue entries on reversible deletion and does not restore consumed playback state',()=>{const {service,editor,player}=setup();const a=song('A');editor.add(service.active,a,0);player.queue.add(a,service.active.id,'Playlist');editor.remove(service.active,a.id);expect(player.queue.entries.isEmpty()).toBe(true);editor.undo();expect(service.active.songs.getSize()).toBe(1);expect(player.queue.entries.isEmpty()).toBe(true);});
});

it('previous after the final ended event skips the current track in playback history',async()=>{
  const {service,player}=setup();const first=song('First'),last=song('Last');service.active.songs.addLast(first);service.active.songs.addLast(last);player.sync();await player.play();await player.next();player.output.element.dispatchEvent(new Event('ended'));expect(player.song).toBe(last);await player.previous();expect(player.song).toBe(first);player.dispose();
});
