import { describe, it, expect, vi, afterEach } from 'vitest';
import { PlaylistBuilder } from '../src/patterns/builder/PlaylistBuilder';
import { LocalFileAudioAdapter, LocalAudioSourceHandler } from '../src/patterns/adapter/LocalFileAudioAdapter';
import { LocalFileSongImporter, SongImporter } from '../src/patterns/factory/SongImporter';
import { NormalPlayback, RepeatOnePlayback, RepeatAllPlayback } from '../src/patterns/bridge/PlaybackMode';
import { BasicTrackPlayback, FadeInDecorator, VolumeBoostDecorator, type TrackPlayback } from '../src/patterns/decorator/TrackPlayback';
import { BrowserStorageHandler } from '../src/storage/StorageHandler';
import { WebPlayerFactory } from '../src/patterns/factory/PlayerEnvironmentFactory';
import { FakeOutput, song } from './helpers';
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); localStorage.clear(); });
describe('Builder and Prototype', () => {
  it('rejects blank names and builds complete configuration', () => { expect(() => new PlaylistBuilder().withName('  ').build()).toThrow(); const playlist = new PlaylistBuilder().withName(' Focus ').withDescription('Study').withRepeatMode('all').build(); expect(playlist.name).toBe('Focus'); expect(playlist.description).toBe('Study'); expect(playlist.repeatMode).toBe('all'); expect(playlist.songs.isEmpty()).toBe(true); });
  it('clones ids, songs, selection, configuration and independent nodes', () => {
    const original = new PlaylistBuilder().withName('Focus').withDescription('Study').withRepeatMode('all').build(); const a = song('A'); const b = song('B'); original.songs.addLast(a); original.songs.addLast(b); original.songs.setCurrent(b.id);
    const copy = original.clone(); expect(copy.id).not.toBe(original.id); expect(copy.description).toBe('Study'); expect(copy.repeatMode).toBe('all'); expect(copy.songs.head).not.toBe(original.songs.head); expect(copy.songs.tail).not.toBe(original.songs.tail); expect(copy.songs.current?.song.title).toBe('B'); expect(copy.songs.head?.song.id).not.toBe(a.id); expect(a.source.retain).toHaveBeenCalledOnce(); copy.songs.removeAt(0); expect(original.songs.getSize()).toBe(2); expect(original.songs.head?.next).toBe(original.songs.tail); copy.songs.addFirst(song('C')); expect(original.songs.getAt(0)).toBe(a);
  });
});
describe('Adapter and Factory Method', () => {
  it('retains object URLs until their final owner releases them', () => { const createObjectURL = vi.fn(()=>'blob:real'); const revokeObjectURL = vi.fn(); vi.stubGlobal('URL', {createObjectURL,revokeObjectURL}); const file = new File(['data'],'song.wav',{type:'audio/wav'}); const adapter = new LocalFileAudioAdapter(file); expect(createObjectURL).toHaveBeenCalledWith(file); adapter.retain(); adapter.release(); expect(revokeObjectURL).not.toHaveBeenCalled(); adapter.release(); adapter.release(); expect(revokeObjectURL).toHaveBeenCalledExactlyOnceWith('blob:real'); expect(()=>adapter.retain()).toThrow(); });
  it('uses the importer abstraction and rejects unsupported or empty files', () => { vi.stubGlobal('URL', { createObjectURL: vi.fn(()=>'blob:test'), revokeObjectURL: vi.fn() }); const importer: SongImporter = new LocalFileSongImporter(new LocalAudioSourceHandler()); const imported = importer.import(new File(['data'],'My Track.mp3',{type:'audio/mpeg'})); expect(imported.title).toBe('My Track'); expect(imported.sourceUrl).toBe('blob:test'); expect(imported.fileName).toBe('My Track.mp3'); expect(()=>importer.import(new File(['data'],'notes.txt',{type:'text/plain'}))).toThrow(); expect(()=>importer.import(new File([],'empty.wav',{type:'audio/wav'}))).toThrow(); expect(importer.import(new File(['data'],'unknown.ogg')).title).toBe('unknown'); });
  it('shares a URL across playlist copies without premature revocation', () => { const revokeObjectURL = vi.fn(); vi.stubGlobal('URL', {createObjectURL: vi.fn(()=>'blob:shared'),revokeObjectURL}); const importer = new LocalFileSongImporter(new LocalAudioSourceHandler()); const playlist = new PlaylistBuilder().withName('Original').build(); playlist.songs.addLast(importer.import(new File(['data'],'a.wav',{type:'audio/wav'}))); const copy = playlist.clone(); playlist.dispose(); expect(revokeObjectURL).not.toHaveBeenCalled(); copy.dispose(); expect(revokeObjectURL).toHaveBeenCalledExactlyOnceWith('blob:shared'); });
});
describe('Bridge', () => {
  it.each(['normal','one','all'])('handles the ended event in %s mode', mode => { const output = new FakeOutput(); const playlist = new PlaylistBuilder().withName('Test').build(); const a = song('A'); const b = song('B'); playlist.songs.addLast(a); playlist.songs.addLast(b); const playback = mode === 'normal' ? new NormalPlayback(output) : mode === 'one' ? new RepeatOnePlayback(output) : new RepeatAllPlayback(output); expect(playback.onEnded(playlist)).toBe(mode === 'one' ? a : b); playlist.songs.setCurrent(b.id); expect(playback.onEnded(playlist)).toBe(mode === 'normal' ? null : mode === 'one' ? b : a); });
  it('handles an empty list in every mode', () => { const playlist = new PlaylistBuilder().withName('Empty').build(); const output = new FakeOutput(); for (const mode of [new NormalPlayback(output),new RepeatOnePlayback(output),new RepeatAllPlayback(output)]) expect(mode.onEnded(playlist)).toBeNull(); });
});
describe('Decorator', () => {
  it('combines fade and boost, clamps volume and cancels fade on pause', async () => { vi.useFakeTimers(); const output = new FakeOutput(); const playback: TrackPlayback = new FadeInDecorator(new VolumeBoostDecorator(new BasicTrackPlayback(output)),1000); playback.setVolume(.8); await playback.play(); expect(output.element.volume).toBe(0); vi.advanceTimersByTime(500); expect(output.element.volume).toBeCloseTo(.8 * .48 * 1.35); vi.advanceTimersByTime(600); expect(output.element.volume).toBe(1); expect(vi.getTimerCount()).toBe(0); await playback.play(); playback.pause(); expect(vi.getTimerCount()).toBe(0); playback.dispose(); });
  it('restores volume and creates no timer after a rejected play', async () => { vi.useFakeTimers(); const output = new FakeOutput(); output.play.mockRejectedValueOnce(new Error('Blocked')); const playback = new FadeInDecorator(new BasicTrackPlayback(output)); playback.setVolume(.4); await expect(playback.play()).rejects.toThrow(); expect(output.element.volume).toBe(.4); expect(vi.getTimerCount()).toBe(0); });
  it('does not start a stale fade after pausing a pending play', async () => { vi.useFakeTimers(); const output = new FakeOutput(); let resolve!: ()=>void; output.play.mockImplementationOnce(()=>new Promise<void>(done=>{resolve=done;})); const playback = new FadeInDecorator(new BasicTrackPlayback(output)); const pending = playback.play(); playback.pause(); resolve(); await pending; expect(vi.getTimerCount()).toBe(0); });
});
describe('Browser environment', () => {
  it('stores configuration without files and rejects malformed data', () => { const storage = new BrowserStorageHandler(); expect(storage.save([{name:'Focus',description:'Study',repeatMode:'all'}])).toBe(true); expect(storage.load()).toEqual([{name:'Focus',description:'Study',repeatMode:'all'}]); localStorage.setItem('sonaris.playlists','invalid'); expect(storage.load()).toEqual([]); localStorage.setItem('sonaris.playlists',JSON.stringify([{name:' '},{name:'Test',description:'',repeatMode:'bad'}])); expect(storage.load()).toEqual([]); });
  it('creates compatible web products through Abstract Factory', () => { const factory = new WebPlayerFactory(); expect(factory.createSources()).toBeInstanceOf(LocalAudioSourceHandler); expect(factory.createStorage()).toBeInstanceOf(BrowserStorageHandler); expect(factory.createOutput().element).toBeInstanceOf(HTMLAudioElement); expect(factory.createConfiguration().initialVolume).toBeGreaterThan(0); });
});
