import { describe, it, expect, vi } from 'vitest';
import { AudioPlayerService } from '../src/services/AudioPlayerService';
import { PlaylistService } from '../src/services/PlaylistService';
import { PlaylistBuilder } from '../src/patterns/builder/PlaylistBuilder';
import { FakeOutput, song } from './helpers';
const configuration = { initialVolume:.65,fadeDuration:1000,boostFactor:1.35 };
const setup = () => { const output = new FakeOutput(); const player = new AudioPlayerService(output,configuration); const playlist = new PlaylistBuilder().withName('Music').build(); playlist.songs.addLast(song('A')); playlist.songs.addLast(song('B')); player.attach(playlist); return {output,player,playlist}; };
describe('AudioPlayerService', () => {
  it('does not play or navigate without songs', async () => { const output = new FakeOutput(); const player = new AudioPlayerService(output,configuration); player.attach(new PlaylistBuilder().withName('Empty').build()); expect(await player.play()).toBe(false); expect(await player.next()).toBe(false); expect(await player.previous()).toBe(false); expect(output.play).not.toHaveBeenCalled(); });
  it('loads adapters, plays, pauses, seeks and clamps volume', async () => { const {output,player} = setup(); expect(output.load).toHaveBeenLastCalledWith(player.song?.source); expect(await player.play()).toBe(true); expect(player.state).toBe('playing'); player.pause(); expect(player.state).toBe('paused'); player.song!.duration = 100; player.seek(.25); expect(output.seek).toHaveBeenCalledWith(25); player.setVolume(2); expect(output.element.volume).toBe(1); player.setVolume(-1); expect(output.element.volume).toBe(0); });
  it('navigates the actual current node and respects boundaries', async () => { const {player,playlist} = setup(); const head = playlist.songs.head; await player.play(); expect(await player.next()).toBe(true); expect(playlist.songs.current).toBe(head?.next); expect(player.state).toBe('playing'); expect(await player.next()).toBe(false); expect(await player.previous()).toBe(true); expect(playlist.songs.current).toBe(head); expect(await player.previous()).toBe(false); });
  it('switches playlists safely and preserves their independent selections', async () => { const {player,playlist,output} = setup(); await player.next(); await player.play(); const second = new PlaylistBuilder().withName('Other').build(); second.songs.addLast(song('C')); player.attach(second); expect(player.state).toBe('paused'); expect(output.load).toHaveBeenLastCalledWith(second.songs.current?.song.source); expect(playlist.songs.current).toBe(playlist.songs.tail); player.attach(playlist); expect(player.song?.title).toBe('B'); });
  it('syncs after deleting current and final songs', async () => { const {player,playlist,output} = setup(); await player.play(); player.stop(); playlist.songs.removeAt(0)?.dispose(); player.sync(); expect(player.song?.title).toBe('B'); expect(player.state).toBe('paused'); player.stop(); playlist.songs.removeAt(0)?.dispose(); player.sync(); expect(player.song).toBeNull(); expect(output.load).toHaveBeenLastCalledWith(null); expect(player.state).toBe('idle'); });
  it('updates metadata and surfaces decoding errors', () => { const {player,output} = setup(); Object.defineProperty(output.element,'duration',{value:73,configurable:true}); output.element.dispatchEvent(new Event('loadedmetadata')); expect(player.duration).toBe(73); const error = vi.fn(); player.addEventListener('playbackerror',error); output.element.dispatchEvent(new Event('error')); expect(error).toHaveBeenCalledOnce(); expect(player.state).toBe('error'); });
  it('handles play rejection without unhandled promise errors', async () => { const {player,output} = setup(); output.play.mockRejectedValueOnce(new Error('Unsupported')); expect(await player.play()).toBe(false); expect(player.state).toBe('error'); });
  it.each(['normal','one','all'] as const)('auto advances with %s repeat mode', async mode => { const {player,playlist,output} = setup(); player.setMode(mode); playlist.songs.setCurrent(playlist.songs.tail!.song.id); player.sync(); output.element.dispatchEvent(new Event('ended')); await vi.waitFor(()=> { if (mode==='normal') expect(player.state).toBe('paused'); else expect(player.state).toBe('playing'); }); expect(player.song?.title).toBe(mode==='all'?'A':'B'); });
  it('ignores a rejected stale play after a playlist change', async () => { const {player,output} = setup(); let reject!: (reason: Error)=>void; output.play.mockImplementationOnce(()=>new Promise<void>((_,fail)=>{reject=fail;})); const pending = player.play(); player.attach(new PlaylistBuilder().withName('Empty').build()); reject(new Error('Aborted')); expect(await pending).toBe(false); expect(player.state).toBe('idle'); });
  it('combines decorators through the service', async () => { const {player,output} = setup(); await player.setEffects(false,true); player.setVolume(.5); expect(output.element.volume).toBeCloseTo(.675); expect(player.boostEnabled).toBe(true); player.dispose(); expect(output.load).toHaveBeenLastCalledWith(null); });
});
describe('PlaylistService', () => {
  it('creates, selects, renames, duplicates and deletes independent playlists', () => { const storage = { load: ()=>[],save: vi.fn(()=>true) }; const service = new PlaylistService(storage); const first = service.active; first.songs.addLast(song()); const second = service.create(' Second '); service.select(second.id); service.rename('Renamed'); expect(second.name).toBe('Renamed'); expect(first.songs.getSize()).toBe(1); const copy = service.duplicate(); expect(copy.id).not.toBe(second.id); expect(service.playlists.size).toBe(3); service.deleteActive(); expect(service.playlists.has(second.id)).toBe(false); expect(()=>service.rename(' ')).toThrow(); expect(()=>service.select('missing')).toThrow(); expect(storage.save).toHaveBeenCalled(); });
  it('restores configurations with empty lists', () => { const service = new PlaylistService({load:()=>[{name:'Saved',description:'Description',repeatMode:'all'}],save:()=>true}); expect(service.active.name).toBe('Saved'); expect(service.active.repeatMode).toBe('all'); expect(service.active.songs.isEmpty()).toBe(true); service.deleteActive(); expect(service.playlists.size).toBe(1); expect(service.active.name).toBe('Favoritas'); });
});
