import { afterEach, describe, expect, it, vi } from 'vitest';
import { Playlist } from '../src/models/Playlist';
import { AudioPlayerService } from '../src/services/AudioPlayerService';
import { ShufflePlayback } from '../src/patterns/bridge/PlaybackMode';
import { BrowserStorageHandler } from '../src/storage/StorageHandler';
import { PlaylistService } from '../src/services/PlaylistService';
import { FakeOutput, song } from './helpers';
const cleanup: (() => void)[] = [];
afterEach(() => { cleanup.splice(0).forEach(dispose => dispose()); vi.restoreAllMocks(); localStorage.clear(); });
function setup(size = 4) {
  const playlist = new Playlist('Shuffle'), output = new FakeOutput();
  for (let i = 0; i < size; i++) playlist.songs.addLast(song(String(i)));
  const player = new AudioPlayerService(output, { initialVolume: .65, fadeDuration: 1000, boostFactor: 1.35 }); player.attach(playlist); player.setMode('shuffle');
  cleanup.push(() => { player.dispose(); playlist.dispose(); }); return { playlist, output, player };
}
async function end(player: AudioPlayerService, output: FakeOutput) { output.element.dispatchEvent(new Event('ended')); await vi.waitFor(() => expect(player.state).not.toBe('loading')); await Promise.resolve(); }
describe('Local shuffle over real linked nodes', () => {
  it('supports an empty list with disabled navigation', async () => { const { player, output } = setup(0); expect(await player.play()).toBe(false); expect(await player.next()).toBe(false); expect(await player.previous()).toBe(false); expect(player.canNext).toBe(false); expect(player.canPrevious).toBe(false); await end(player, output); });
  it('finishes one song once and only starts another cycle on explicit Play', async () => { const { player, output } = setup(1); await player.play(); expect(player.canNext).toBe(false); await end(player, output); expect(player.shuffleFinished).toBe(true); expect(player.state).toBe('paused'); expect(output.play).toHaveBeenCalledTimes(1); await player.play(); expect(player.shuffleFinished).toBe(false); expect(output.play).toHaveBeenCalledTimes(2); });
  it('uses reservoir sampling without reordering or replacing the original nodes', () => { const { playlist, output } = setup(8); const mode = new ShufflePlayback(output, () => 0), original = playlist.songs.readSnapshot(), head = playlist.songs.head, tail = playlist.songs.tail; mode.reset(playlist); const visited = new Set([playlist.songs.current!.song.id]); for (let i = 1; i < 8; i++) { const next = mode.next(playlist)!; expect(visited.has(next.id)).toBe(false); visited.add(next.id); } expect(mode.next(playlist)).toBeNull(); expect(visited.size).toBe(8); expect(playlist.songs.head).toBe(head); expect(playlist.songs.tail).toBe(tail); expect(playlist.songs.readSnapshot().map(node => [node.id,node.previousId,node.nextId])).toEqual(original.map(node => [node.id,node.previousId,node.nextId])); playlist.songs.assertIntegrity(); });
  it('automatically plays every song exactly once and pauses at cycle end', async () => { const { player, output } = setup(5); await player.play(); const played = new Set([player.song!.id]); for (let i = 1; i < 5; i++) { await end(player, output); expect(played.has(player.song!.id)).toBe(false); played.add(player.song!.id); } await end(player, output); expect(player.shuffleFinished).toBe(true); expect(player.state).toBe('paused'); expect(output.play).toHaveBeenCalledTimes(5); });
  it('Previous and Next retrace the real random history before selecting an unvisited song', async () => { const { player } = setup(5); await player.play(); const a = player.song!.id; await player.next(); const b = player.song!.id; await player.next(); const c = player.song!.id; await player.previous(); expect(player.song!.id).toBe(b); await player.previous(); expect(player.song!.id).toBe(a); expect(player.canPrevious).toBe(false); await player.next(); expect(player.song!.id).toBe(b); await player.next(); expect(player.song!.id).toBe(c); await player.next(); expect([a,b,c]).not.toContain(player.song!.id); });
  it('replays history correctly while paused, including after exhaustion', async () => { const { player, output } = setup(3); await player.play(); const a = player.song!.id; await player.next(); const b = player.song!.id; await player.next(); const c = player.song!.id; await end(player, output); await player.previous(); expect(player.song!.id).toBe(b); await player.previous(); expect(player.song!.id).toBe(a); await player.next(); expect(player.song!.id).toBe(b); await player.next(); expect(player.song!.id).toBe(c); expect(player.state).toBe('paused'); });
  it('gives a manual queue priority without automatic re-selection of its active-playlist track', async () => { const { player, playlist } = setup(3); await player.play(); const queued = playlist.songs.tail!.song; player.queue.add(queued, playlist.id, playlist.name); await player.next(); expect(player.song!.title).toBe(queued.title); expect(player.isQueued).toBe(true); await player.next(); expect(player.song!.title).not.toBe(queued.title); expect(player.canNext).toBe(false); });
  it('keeps foreign queue sources and backward history separate from the active cycle', async () => { const { player } = setup(2); const foreign = song('Foreign'); cleanup.push(() => foreign.dispose()); await player.play(); const first = player.song!.id; player.queue.add(foreign, 'foreign-list', 'Foreign'); await player.next(); expect(player.isQueued).toBe(true); await player.previous(); expect(player.song!.id).toBe(first); await player.next(); expect(player.song!.title).toBe('Foreign'); await player.next(); expect(player.isQueued).toBe(false); expect(player.song!.id).not.toBe(first); });
  it('preserves queued original identifiers through backward and forward replay', async () => { const { player, playlist } = setup(3); await player.play(); const queued = playlist.songs.tail!.song; player.queue.add(queued,playlist.id,playlist.name); await player.next(); await player.previous(); await player.next(); expect(player.song!.id).toBe(queued.id); await player.next(); expect(player.song!.id).not.toBe(queued.id); expect(player.canNext).toBe(false); });
  it('retains the complete shuffle cycle history beyond the normal 50-entry limit', async () => { const { player } = setup(55); await player.play(); const first = player.song!.id; for (let i=1;i<55;i++) await player.next(); for (let i=1;i<55;i++) expect(await player.previous()).toBe(true); expect(player.song!.id).toBe(first); expect(player.canPrevious).toBe(false); });
  it('explicit selection starts a new cycle without changing playlist order', async () => { const { player, playlist } = setup(2); await player.play(); await player.next(); expect(player.canNext).toBe(false); player.select(playlist.songs.head!.song.id); expect(player.canNext).toBe(true); await player.play(); await player.next(); expect(player.song!.id).toBe(playlist.songs.tail!.song.id); });
  it('still gives a new manual queue entry priority at cycle completion', async () => { const { player, playlist, output } = setup(1); await player.play(); player.queue.add(playlist.songs.head!.song,playlist.id,playlist.name); await end(player,output); expect(player.isQueued).toBe(true); expect(player.state).toBe('playing'); await end(player,output); expect(player.shuffleFinished).toBe(true); });
  it('adding a manual queue after exhaustion does not silently restart the automatic cycle', async () => { const { player, playlist, output } = setup(2); await player.play(); await player.next(); await end(player,output); expect(player.shuffleFinished).toBe(true); player.queue.add(playlist.songs.head!.song,playlist.id,playlist.name); await player.next(); expect(player.shuffleFinished).toBe(false); await player.play(); await end(player,output); expect(player.shuffleFinished).toBe(true); expect(player.canNext).toBe(false); });
  it('changes modes during playback without loading, restarting or pausing the current song', async () => { const { player, output } = setup(3); await player.play(); output.element.currentTime = 12; const current = player.song; output.load.mockClear(); output.pause.mockClear(); for (const mode of ['normal','one','all','shuffle'] as const) { player.setMode(mode); expect(player.song).toBe(current); expect(player.state).toBe('playing'); expect(player.currentTime).toBe(12); } expect(output.load).not.toHaveBeenCalled(); expect(output.pause).not.toHaveBeenCalled(); });
  it('does not reset a cycle when shuffle is selected again', async () => { const { player } = setup(2); await player.play(); await player.next(); player.setMode('shuffle'); expect(player.canNext).toBe(false); });
  it('adapts to additions, removals and reordering while preserving links', async () => { const { player, playlist } = setup(3); await player.play(); const removed = playlist.songs.removeAt(1); removed.dispose(); const added = song('New'); playlist.songs.addLast(added); playlist.songs.moveNode(2,0); const played = new Set([player.song!.id]); while (player.canNext) { await player.next(); expect(played.has(player.song!.id)).toBe(false); played.add(player.song!.id); } expect(played.has(added.id)).toBe(true); expect(played.size).toBe(3); playlist.songs.assertIntegrity(); });
  it('restores shuffle preferences through storage and preserves them in clones', () => { const storage = new BrowserStorageHandler(); storage.save([{name:'Saved',description:'',repeatMode:'shuffle'}]); const library = new PlaylistService(storage); cleanup.push(() => library.dispose()); expect(library.active.repeatMode).toBe('shuffle'); expect(library.active.clone().repeatMode).toBe('shuffle'); });
  it('clears the cycle and forward history when attaching another playlist', async () => { const { player } = setup(3); await player.play(); await player.next(); await player.previous(); const other = new Playlist('Other', '', 'shuffle'); other.songs.addLast(song('Only')); cleanup.push(() => other.dispose()); player.attach(other); expect(player.canPrevious).toBe(false); expect(player.canNext).toBe(false); expect(player.song!.title).toBe('Only'); });
});
