import { describe, expect, it, vi } from 'vitest';
import { normalizeSpotifyTrack, SpotifyCatalogAdapter, artworkUrl } from '../src/spotify/SpotifyCatalogAdapter';
import { SpotifyReferenceCollection } from '../src/spotify/SpotifyReferenceCollection';
import type { SpotifyApiClient } from '../src/spotify/SpotifyApiClient';
import { LocalMusicProvider } from '../src/music/LocalMusicProvider';
import { PlaylistService } from '../src/services/PlaylistService';
import { AudioPlayerService } from '../src/services/AudioPlayerService';
import { FakeOutput, song } from './helpers';
const id = 'A'.repeat(22), other = 'B'.repeat(22), artist = 'C'.repeat(22);
const track = (trackId = id) => ({ id: trackId, name: '<Tagged track>', duration_ms: 180000, artists: [{ name: 'Fixture artist' }], album: { name: 'Fixture album', images: [{ url: 'https://i.scdn.co/image/fixture' }] } });
function setup() { const call = vi.fn(async (_path: string, _method?: string, _body?: unknown, _signal?: AbortSignal) => ({ tracks: { total: 25, items: [track(), track(), track(other), { id: 'invalid' }] } })); return { call, catalog: new SpotifyCatalogAdapter({ call } as unknown as SpotifyApiClient) }; }
describe('Spotify catalog with fixtures, not live results', () => {
  it('normalizes stable composite identifiers, duration and official references without previews', () => { expect(normalizeSpotifyTrack(track())).toMatchObject({ id: 'spotify:' + id, duration: 180, title: '<Tagged track>', spotifyUri: 'spotify:track:' + id, playbackCapability: 'spotify-premium' }); expect(normalizeSpotifyTrack({ ...track(), preview_url: 'https://evil.example/audio.mp3' })).not.toHaveProperty('preview_url'); });
  it('filters invalid records, restricted tracks and unsafe artwork URLs', () => { expect(normalizeSpotifyTrack({ id: 'wrong', name: 'Track' })).toBeNull(); expect(normalizeSpotifyTrack({ ...track(), is_playable: false })!.playbackCapability).toBe('unavailable'); expect(normalizeSpotifyTrack({ ...track(), restrictions: { reason: 'market' } })!.playbackCapability).toBe('unavailable'); expect(artworkUrl('javascript:alert(1)')).toBeNull(); expect(artworkUrl('https://scdn.co.evil.example/image')).toBeNull(); expect(artworkUrl('https://user:pass@i.scdn.co/image')).toBeNull(); expect(artworkUrl('https://i.scdn.co/image/fixture')).toBeTruthy(); });
  it('uses limit 10, offset pagination and deduplicates tracks', async () => { const { catalog, call } = setup(); const page = await catalog.search(' piano ', 'track', 10); expect(page.tracks).toHaveLength(2); expect(page.nextOffset).toBe(20); expect(call.mock.calls[0][0]).toContain('limit=10'); expect(call.mock.calls[0][0]).toContain('offset=10'); expect(call.mock.calls[0][0]).toContain('q=piano'); });
  it('handles artists, albums, empty queries and pagination boundary', async () => { const { catalog, call } = setup(); call.mockResolvedValue({ artists: { total: 2, items: [{ id: artist, name: 'Fixture artist', images: [] }] } } as never); const page = await catalog.search('Artist', 'artist'); expect(page.entities[0].externalUrl).toBe('https://open.spotify.com/artist/' + artist); expect(page.nextOffset).toBeNull(); expect((await catalog.search('', 'track')).tracks).toEqual([]); await expect(catalog.search('Track', 'track', 1001)).rejects.toThrow(); });
  it('explores only official artist-album and album-tracks endpoints and propagates restrictions', async () => { const { catalog, call } = setup(); call.mockResolvedValueOnce({ items: [{ id, name: 'Album', artists: [{ name: 'Artist' }] }], total: 1 } as never); expect((await catalog.artistAlbums(artist)).entities).toHaveLength(1); expect(call.mock.calls[0][0]).toBe(`/artists/${artist}/albums?limit=10&offset=0`); call.mockResolvedValueOnce({ id, name: 'Album', images: [] } as never).mockResolvedValueOnce({ total: 1, items: [track(other)] } as never); expect((await catalog.albumTracks(id)).tracks[0].albumName).toBe('Album'); call.mockRejectedValueOnce(new Error('Forbidden')); await expect(catalog.artistAlbums(artist)).rejects.toThrow('Forbidden'); });
  it('rejects identifier injection and forwards cancellation', async () => { const { catalog, call } = setup(); await expect(catalog.albumTracks('../me')).rejects.toThrow(); const controller = new AbortController(); await catalog.search('Query', 'track', 0, controller.signal); expect((call.mock.calls[0] as unknown[])[3]).toBe(controller.signal); });
  it('keeps a separate doubly linked in-memory reference collection with bounded deduplication', () => { const collection = new SpotifyReferenceCollection(), a = normalizeSpotifyTrack(track())!, b = normalizeSpotifyTrack(track(other))!; expect(collection.add(a)).toBe(true); expect(collection.add(a)).toBe(false); collection.add(b); collection.move(b.id, -1); expect(collection.tracks.head?.song.id).toBe(b.id); expect(collection.tracks.tail?.previous).toBe(collection.tracks.head); collection.remove(b.id); expect(collection.tracks.current).toBe(collection.tracks.head); collection.tracks.assertIntegrity(); collection.clear(); expect(collection.tracks.isEmpty()).toBe(true); });
  it('never treats Spotify references as local files or modifies local playlists', async () => { const library = new PlaylistService({ load: () => [], save: () => true }), player = new AudioPlayerService(new FakeOutput(), { initialVolume: .65, fadeDuration: 1000, boostFactor: 1.35 }), original = song('Local'); library.active.songs.addLast(original); const copy = library.active.clone(); library.playlists.set(copy.id, copy); const local = new LocalMusicProvider(library, player); expect((await local.search('Local', 'track')).tracks).toHaveLength(1); expect((await local.search('Local', 'track')).tracks[0].spotifyUri).toBeNull(); const collection = new SpotifyReferenceCollection(); collection.add(normalizeSpotifyTrack(track())!); expect(library.active.songs.getSize()).toBe(1); expect(library.active.songs.head?.song).toBe(original); });
});
