import type { AudioProcessingService,FrequencyBand,EqualizerPreset } from '../audio/AudioProcessingService';
import type { AudioPlayerService } from '../services/AudioPlayerService';
import type { PlaylistService } from '../services/PlaylistService';
import type { StatisticsService } from '../services/StatisticsService';
import type { OfflineLibraryService } from '../services/OfflineLibraryService';
import type { SleepTimerService } from '../services/SleepTimerService';
import type { PwaService } from '../offline/PwaService';
import { keyboardShortcuts } from '../services/KeyboardShortcutService';
import { AudioVisualizer,type VisualizationMode } from './AudioVisualizer';
import { escapeHtml,formatTime } from './formatters';
export class AdvancedView {
  private readonly visualizer: AudioVisualizer;
  private notificationTimer: ReturnType<typeof setTimeout>|null=null;
  constructor(private readonly container: HTMLElement,private readonly playlists: PlaylistService,private readonly player: AudioPlayerService,private readonly processing: AudioProcessingService,private readonly statistics: StatisticsService,private readonly offline: OfflineLibraryService,private readonly timer: SleepTimerService,private readonly pwa: PwaService) {
    this.shell();this.visualizer=new AudioVisualizer(this.get<HTMLCanvasElement>('audio-visualizer'),processing,player);this.bind();
    player.queue.addEventListener('change',()=>this.renderQueue());statistics.addEventListener('change',()=>this.renderStatistics());
    statistics.addEventListener('storageerror',()=>this.notify('No se pudieron guardar las estadísticas. La reproducción sigue disponible.'));
    offline.addEventListener('change',()=>this.renderOffline());pwa.addEventListener('change',()=>this.renderOffline());timer.addEventListener('change',()=>this.renderTimer());timer.addEventListener('finished',()=>this.notify('Temporizador finalizado. La reproducción se detuvo.'));
    this.refresh();
  }
  private get<T extends HTMLElement=HTMLElement>(id:string):T{return this.container.querySelector<T>(`#${id}`)!;}
  private shell(): void {
    const bands=[['bass','Graves'],['mid','Medios'],['treble','Agudos']];
    this.container.innerHTML=`<section class="advanced-workspace" aria-labelledby="advanced-title"><div class="advanced-heading"><div><span class="eyebrow">ESCUCHA, ORGANIZA, DESCUBRE</span><h2 id="advanced-title">Más para tu música</h2></div><button class="quiet-button" data-feature="help">Atajos de teclado</button></div><div class="feature-tabs" role="tablist" aria-label="Herramientas de Sonaris">${[['audio','Audio'],['queue','Cola'],['stats','Mis estadísticas'],['sleep','Temporizador'],['offline','Sin conexión']].map(([id,label],index)=>`<button role="tab" id="tab-${id}" aria-controls="panel-${id}" aria-selected="${index===0}" tabindex="${index===0?'0':'-1'}" data-tab="${id}">${label}${id==='queue'?' <span id="queue-count" class="small-badge">0</span>':''}</button>`).join('')}</div>
    <section id="panel-audio" class="feature-panel" role="tabpanel" aria-labelledby="tab-audio"><div class="feature-panel-header"><h3>Visualizador</h3><div class="inline-controls"><label for="visualization-mode" class="sr-only">Tipo de visualización</label><select id="visualization-mode"><option value="bars">Barras</option><option value="wave">Ondas</option></select><button id="toggle-visualizer" class="button primary" data-feature="visualizer">Activar visualizador</button></div></div><canvas id="audio-visualizer" width="720" height="150" role="img" aria-label="Visualizador de frecuencias y ondas de la canción actual"></canvas><p class="feature-note">Datos reales de la canción. La animación se detiene al pausar u ocultar el panel.</p><div class="feature-panel-header"><h3>Ecualizador</h3><div class="inline-controls"><label for="equalizer-preset">Preset</label><select id="equalizer-preset"><option value="normal">Normal</option><option value="pop">Pop</option><option value="rock">Rock</option><option value="classical">Clásica</option><option value="custom">Personalizado</option></select><button class="quiet-button" data-feature="reset-equalizer">Restablecer</button></div></div><div class="equalizer-bands">${bands.map(([band,label])=>`<label for="band-${band}">${label}<input id="band-${band}" data-band="${band}" type="range" min="-6" max="6" step="0.5" value="0"><output id="value-${band}" for="band-${band}">0 dB</output></label>`).join('')}</div><p class="feature-note">Una sola ruta de audio, con compensación y limitador. Los efectos del reproductor siguen funcionando.</p></section>
    <section id="panel-queue" class="feature-panel" role="tabpanel" aria-labelledby="tab-queue" hidden><div class="feature-panel-header"><h3>Cola de reproducción</h3><button class="quiet-button danger" data-feature="clear-queue">Vaciar cola</button></div><p class="feature-note">Tiene prioridad sobre el avance y la repetición. Añade canciones desde el menú ⋯ de cada fila.</p><div id="queue-list"></div></section>
    <section id="panel-stats" class="feature-panel" role="tabpanel" aria-labelledby="tab-stats" hidden><h3>Mis estadísticas</h3><div class="stat-cards"><div><strong id="stats-total">0</strong><span>Canciones reproducidas</span></div><div><strong id="stats-minutes">0</strong><span>Minutos escuchados</span></div><div><strong id="stats-playlist">—</strong><span>Playlist más utilizada</span></div></div><label class="threshold-control" for="stats-threshold">Tiempo mínimo para contar una reproducción<input id="stats-threshold" type="number" min="1" max="60" step="1" value="5"> segundos</label><div class="stats-columns"><div><h4>Canciones más escuchadas</h4><div id="stats-ranking"></div></div><div><h4>Últimas canciones reproducidas</h4><div id="stats-recent"></div></div></div><h4>Tiempo de escucha por día</h4><div id="weekly-activity"></div><p class="feature-note">Actividad de los últimos siete días. Seleccionar, adelantar el tiempo o repetir eventos no cuenta como escucha.</p></section>
    <section id="panel-sleep" class="feature-panel" role="tabpanel" aria-labelledby="tab-sleep" hidden><h3>Temporizador para dormir</h3><p class="feature-note">La salida disminuye durante los últimos diez segundos. Al cancelar o terminar, tu volumen configurado se conserva.</p><div class="sleep-controls"><label for="sleep-duration">Detener después de</label><select id="sleep-duration"><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="custom">Tiempo personalizado</option></select><label id="sleep-custom-label" for="sleep-custom" hidden>Minutos<input id="sleep-custom" type="number" min="0.01" max="1440" step="0.01" value="10"></label><button class="button primary" data-feature="start-timer">Iniciar temporizador</button><button id="cancel-timer" class="quiet-button" data-feature="cancel-timer">Cancelar temporizador</button></div><div class="timer-readout"><span>Tiempo restante</span><strong id="sleep-remaining" role="timer">Sin temporizador</strong></div></section>
    <section id="panel-offline" class="feature-panel" role="tabpanel" aria-labelledby="tab-offline" hidden><h3>Tu biblioteca sin conexión</h3><p class="feature-note">Solo se guardan archivos que eliges conservar. Son locales a este navegador; no se suben a servidores. El navegador puede eliminar datos si necesita espacio.</p><p id="offline-status" role="status"></p><p id="cache-status"></p><div class="offline-controls"><button class="button primary" id="save-library" data-feature="save-library">Conservar canciones de esta playlist</button><button class="quiet-button" data-feature="prepare-offline">Preparar modo sin conexión</button><button class="quiet-button" data-feature="request-persistence">Solicitar almacenamiento persistente</button><button class="quiet-button danger" data-feature="clear-audio">Eliminar todos los archivos guardados</button></div><p id="storage-usage" class="feature-note"></p><div id="saved-files"></div></section>
    <p id="advanced-message" class="advanced-message" role="status" aria-live="polite" hidden></p></section><dialog id="shortcuts-dialog" aria-labelledby="shortcuts-title"><h2 id="shortcuts-title">Atajos de teclado</h2><p>Funcionan fuera de campos de texto y controles interactivos. Las combinaciones del navegador y del sistema se respetan.</p><dl class="shortcut-list">${keyboardShortcuts.map(([key,description])=>`<dt><kbd>${key}</kbd></dt><dd>${description}</dd>`).join('')}</dl><button class="button primary" data-feature="close-help">Cerrar ayuda</button></dialog>`;
  }
  private bind(): void {
    this.container.addEventListener('click',event=>{
      const target=(event.target as HTMLElement).closest<HTMLElement>('[data-tab],[data-feature]');if(!target)return;
      if(target.dataset.tab){this.selectTab(target.dataset.tab);return;}
      void this.action(target.dataset.feature!,target.dataset.id).catch(()=>this.notify('No se pudo completar la operación. Revisa el estado del navegador o del almacenamiento.'));
    });
    this.container.addEventListener('keydown',event=>{const target=event.target as HTMLElement;if(target.getAttribute('role')!=='tab' || !['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...this.container.querySelectorAll<HTMLButtonElement>('[role="tab"]')];const index=tabs.indexOf(target as HTMLButtonElement);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;this.selectTab(tabs[next].dataset.tab!);tabs[next].focus();});
    this.get<HTMLSelectElement>('visualization-mode').addEventListener('change',event=>this.visualizer.setMode((event.target as HTMLSelectElement).value as VisualizationMode));
    this.get<HTMLSelectElement>('equalizer-preset').addEventListener('change',event=>{const preset=(event.target as HTMLSelectElement).value as EqualizerPreset;void this.processing.resume().then(()=>{this.processing.setPreset(preset);this.renderEqualizer();}).catch(()=>this.notify('El navegador no pudo activar el procesamiento de audio.'));});
    this.container.querySelectorAll<HTMLInputElement>('[data-band]').forEach(input=>input.addEventListener('input',()=>{const gain=Number(input.value),band=input.dataset.band as FrequencyBand;void this.processing.resume().then(()=>{this.processing.setBand(band,gain);this.renderEqualizer();}).catch(()=>this.notify('No se pudo cambiar el ecualizador.'));}));
    this.get<HTMLInputElement>('stats-threshold').addEventListener('change',event=>this.statistics.setThreshold(Number((event.target as HTMLInputElement).value)));
    this.get<HTMLSelectElement>('sleep-duration').addEventListener('change',()=>{this.get('sleep-custom-label').hidden=this.get<HTMLSelectElement>('sleep-duration').value!=='custom';});
  }
  private selectTab(id: string): void {
    this.container.querySelectorAll<HTMLElement>('[role="tab"]').forEach(tab=>{const selected=tab.dataset.tab===id;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;if(selected)tab.scrollIntoView?.({block:'nearest',inline:'nearest'});});
    this.container.querySelectorAll<HTMLElement>('[role="tabpanel"]').forEach(panel=>{panel.hidden=panel.id!==`panel-${id}`;});this.visualizer.setVisible(id==='audio');
    if(id==='offline')void this.offline.estimate().then(estimate=>{this.get('storage-usage').textContent=estimate?`Espacio usado: ${((estimate.usage??0)/1048576).toFixed(1)} MB de ${((estimate.quota??0)/1048576).toFixed(0)} MB disponibles para este origen.`:'El navegador no informa el espacio disponible.';}).catch(()=>this.notify('No se pudo consultar el espacio disponible.'));
  }
  private async action(action: string,id?: string): Promise<void> {
    if(action==='help')this.get<HTMLDialogElement>('shortcuts-dialog').showModal();
    else if(action==='close-help')this.get<HTMLDialogElement>('shortcuts-dialog').close();
    else if(action==='visualizer'){try{await this.visualizer.enable(!this.visualizer.enabled);this.get('toggle-visualizer').textContent=this.visualizer.enabled?'Desactivar visualizador':'Activar visualizador';}catch{this.notify('No se pudo activar el visualizador en este navegador.');}}
    else if(action==='reset-equalizer'){this.processing.setPreset('normal');this.renderEqualizer();}
    else if(action==='clear-queue')this.player.queue.clear();
    else if(action==='remove-queue' && id)this.player.queue.remove(id);
    else if((action==='queue-up'||action==='queue-down')&&id)this.player.queue.move(id,action==='queue-up'?-1:1);
    else if(action==='cancel-timer')this.timer.cancel();
    else if(action==='start-timer'){const value=this.get<HTMLSelectElement>('sleep-duration').value;const minutes=Number(value==='custom'?this.get<HTMLInputElement>('sleep-custom').value:value);try{this.timer.start(minutes);}catch{this.notify('Elige un tiempo entre 0,01 y 1440 minutos.');}}
    else if(action==='prepare-offline'){try{await this.pwa.prepare();this.renderOffline();}catch{this.notify(import.meta.env.PROD?'No se pudieron preparar los recursos sin conexión. Comprueba HTTPS y vuelve a intentarlo.':'Compila y ejecuta la vista previa para preparar el modo sin conexión.');}}
    else if(action==='request-persistence'){await this.offline.requestPersistence();}
    else if(action==='save-library'){try{await this.offline.savePlaylist(this.playlists.active);}catch{this.notify(this.offline.status);}}
    else if(action==='clear-audio'){if(window.confirm('¿Eliminar todos los archivos guardados en este navegador? La sesión actual conservará sus canciones.')){try{await this.offline.clearAudio();}catch{this.notify(this.offline.status);}}}
    else if((action==='save-file'||action==='forget-file')&&id){const position=this.playlists.active.songs.indexOf(id);if(position>=0){try{await this.offline.setSaved([this.playlists.active.songs.getAt(position)],action==='save-file');}catch{this.notify(this.offline.status);}}}
  }
  refresh(): void {this.renderQueue();this.renderStatistics();this.renderEqualizer();this.renderTimer();this.renderOffline();}
  private renderQueue(): void {
    const entries=[...this.player.queue.entries];this.get('queue-count').textContent=String(entries.length);
    this.get('queue-list').innerHTML=entries.length?entries.map((entry,index)=>`<div class="queue-row"><span>${index+1}</span><div><strong>${escapeHtml(entry.song.title)}</strong><small>${escapeHtml(entry.playlistName)}</small></div><button class="quiet-button" data-feature="queue-up" data-id="${entry.id}" ${index===0?'disabled':''}>Mover arriba</button><button class="quiet-button" data-feature="queue-down" data-id="${entry.id}" ${index===entries.length-1?'disabled':''}>Mover abajo</button><button class="quiet-button danger" data-feature="remove-queue" data-id="${entry.id}" aria-label="Quitar de la cola ${escapeHtml(entry.song.title)}">Quitar de la cola</button></div>`).join(''):'<p class="feature-empty">La cola está vacía. El reproductor seguirá el orden de tu playlist.</p>';
  }
  private renderEqualizer():void {this.get<HTMLSelectElement>('equalizer-preset').value=this.processing.preset;for(const band of ['bass','mid','treble'] as const){this.get<HTMLInputElement>(`band-${band}`).value=String(this.processing.gains[band]);this.get(`value-${band}`).textContent=`${this.processing.gains[band]>0?'+':''}${this.processing.gains[band]} dB`;}}
  private renderTimer():void {this.get('sleep-remaining').textContent=this.timer.active?formatTime(Math.ceil(this.timer.remainingSeconds)):'Sin temporizador';this.get<HTMLButtonElement>('cancel-timer').disabled=!this.timer.active;}
  private renderOffline():void {
    this.get('offline-status').textContent=this.playlists.active.temporary?'Guarda la radio como playlist antes de conservar sus archivos sin conexión.':this.offline.status;this.get('cache-status').textContent=this.pwa.status;this.get<HTMLButtonElement>('save-library').disabled=this.offline.busy||this.playlists.active.songs.isEmpty()||this.playlists.active.temporary;
    this.get('saved-files').innerHTML=[...this.playlists.active.songs].map(song=>`<div class="saved-file-row"><span>${escapeHtml(song.title)}<small>${song.savedOffline?'Conservada en este navegador':'Solo disponible en esta sesión'}</small></span><button class="quiet-button" data-feature="${song.savedOffline?'forget-file':'save-file'}" data-id="${song.id}" ${this.offline.busy||this.playlists.active.temporary?'disabled':''}>${song.savedOffline?'Eliminar archivo guardado':'Conservar sin conexión'}</button></div>`).join('')||'<p class="feature-empty">Agrega canciones para conservarlas sin conexión.</p>';
  }
  private renderStatistics():void {
    const stats=this.statistics.snapshot;this.get('stats-total').textContent=String(stats.totalPlays);this.get('stats-minutes').textContent=(stats.totalSeconds/60).toLocaleString('es',{maximumFractionDigits:1});
    const mostUsed=Object.entries(stats.playlists).sort((a,b)=>b[1].seconds-a[1].seconds)[0];this.get('stats-playlist').textContent=mostUsed?(this.playlists.playlists.get(mostUsed[0])?.name??mostUsed[1].name):'Sin actividad';
    const threshold=this.get<HTMLInputElement>('stats-threshold');if(document.activeElement!==threshold)threshold.value=String(stats.threshold);
    this.get('stats-ranking').innerHTML=Object.values(stats.songs).filter(song=>song.plays>0).sort((a,b)=>b.plays-a.plays).slice(0,5).map(song=>`<div class="stat-list-row"><span>${escapeHtml(song.title)}</span><strong>${song.plays} ${song.plays===1?'reproducción':'reproducciones'}</strong></div>`).join('')||'<p class="feature-empty">Aún no hay reproducciones contabilizadas.</p>';
    this.get('stats-recent').innerHTML=stats.recent.map(entry=>`<div class="stat-list-row"><span>${escapeHtml(entry.title)}</span><small>${escapeHtml(new Date(entry.date).toLocaleString('es'))}</small></div>`).join('')||'<p class="feature-empty">Tus próximas escuchas aparecerán aquí.</p>';
    const today=new Date();const days=Array.from({length:7},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()-6+index);const key=new Intl.DateTimeFormat('sv-SE').format(date);return {label:date.toLocaleDateString('es',{weekday:'short'}),seconds:stats.days[key]??0};});const maximum=Math.max(1,...days.map(day=>day.seconds));
    this.get('weekly-activity').innerHTML=`<div class="weekly-chart" role="img" aria-label="${escapeHtml(days.map(day=>`${day.label}: ${(day.seconds/60).toFixed(1)} minutos`).join(', '))}">${days.map(day=>`<div class="activity-day"><small>${(day.seconds/60).toFixed(1)} min</small><div class="activity-track"><span style="height:${day.seconds/maximum*100}%"></span></div><span>${escapeHtml(day.label)}</span></div>`).join('')}</div>`;
  }
  notify(message: string):void {if(this.notificationTimer)clearTimeout(this.notificationTimer);const element=this.get('advanced-message');element.textContent=message;element.hidden=false;this.notificationTimer=setTimeout(()=>{element.hidden=true;},8000);}
  dispose():void {this.visualizer.dispose();if(this.notificationTimer)clearTimeout(this.notificationTimer);}
}
